version: '2'

services:
  app:
    image: eeacms/european.cache.registry
    container_name: ecr.app
    depends_on:
    - mysql
    env_file:
    - .secret
    volumes:
    - /etc/localtime:/etc/localtime:ro

  mysql:
    image: mysql:5.5
    container_name: ecr.db
    environment:
    - MYSQL_DATABASE=ecr
    - MYSQL_USER=ecr
    - MYSQL_PASSWORD=ecr
    - MYSQL_ROOT_PASSWORD=ecr
    volumes:
    - /etc/localtime:/etc/localtime:ro
    - data:/var/lib/mysql

volumes:
  fcs-mysql-data:
    driver: local
