version: '2'

services:
  app:
    image: eeacms/european.cache.registry
    container_name: ecr.app
    depends_on:
    - postgres
    environment:
    - TZ=Europe/Copenhagen
    env_file:
    - .secret

  postgres:
    image: postgres:9-alpine
    container_name: ecr.db
    environment:
    - POSTGRES_PASSWORD=ecr
    - TZ=Europe/Copenhagen
    volumes:
    - data:/var/lib/postgresql/data
    - ./docker/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  data:
    driver: local
