revision = 'b1da65cc5a22'
down_revision = 'd411496edccc'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('undertaking', sa.Column('check_passed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('undertaking', 'check_passed')
    # ### end Alembic commands ###
