from alembic import op
import sqlalchemy as sa

revision = "0030"
down_revision = "0029"


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "undertaking_country_history",
        sa.Column("undertaking_id", sa.Integer(), nullable=False),
        sa.Column("country_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["country_id"],
            ["country.id"],
        ),
        sa.ForeignKeyConstraint(
            ["undertaking_id"],
            ["undertaking.id"],
        ),
        sa.PrimaryKeyConstraint("undertaking_id", "country_id"),
    )
    op.alter_column("licence", "net_mass", existing_type=sa.REAL(), nullable=True)
    op.alter_column("licence", "total_odp_mass", existing_type=sa.REAL(), nullable=True)


def downgrade():
    op.alter_column(
        "licence", "total_odp_mass", existing_type=sa.REAL(), nullable=False
    )
    op.alter_column("licence", "net_mass", existing_type=sa.REAL(), nullable=False)
    op.drop_table("undertaking_country_history")
