"""add_auditors

Revision ID: 0038
Revises: 0037
Create Date: 2024-12-13 10:47:41.523534

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "0038"
down_revision = "0037"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table("auditor",
    sa.Column("id", sa.Integer(), nullable=False),
    sa.Column("auditor_uid", sa.String(length=20), nullable=True),
    sa.Column("name", sa.String(length=255), nullable=True),
    sa.Column("date_created", sa.Date(), nullable=True),
    sa.Column("date_updated", sa.Date(), nullable=True),
    sa.Column("date_created_in_ecr", sa.Date(), server_default=sa.text("now()"), nullable=True),
    sa.Column("date_updated_in_ecr", sa.Date(), nullable=True),
    sa.Column("status", sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint("id")
    )
    op.create_table("auditor_users",
    sa.Column("user_id", sa.Integer(), nullable=True),
    sa.Column("auditor_id", sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(["auditor_id"], ["auditor.id"], ),
    sa.ForeignKeyConstraint(["user_id"], ["user.id"], )
    )
    op.add_column("user", sa.Column("type", sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "type")
    op.drop_table("auditor_users")
    op.drop_table("auditor")
    # ### end Alembic commands ###
