"""Add combined nomenclature and substance nomenclature link
   Add aggregated multi year licence table

Revision ID: 0049
Revises: 0048
Create Date: 2026-02-05 11:06:59.413949

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "0049"
down_revision = "0048"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "substance_nomenclature_combined_nomenclature_link",
        sa.Column("substance_nomenclature_id", sa.Integer(), nullable=True),
        sa.Column("combined_nomenclature_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["combined_nomenclature_id"],
            ["combined_nomenclature.id"],
        ),
        sa.ForeignKeyConstraint(
            ["substance_nomenclature_id"],
            ["substance_nomenclature.id"],
        ),
    )
    op.create_table(
        "multi_year_licence_aggregated",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("multi_year_licence_id", sa.Integer(), nullable=True),
        sa.Column("undertaking_id", sa.Integer(), nullable=True),
        sa.Column("s_orig_country_name", sa.String(length=100), nullable=True),
        sa.Column("organization_country_name", sa.String(length=4), nullable=True),
        sa.Column("year", sa.Integer(), nullable=True),
        sa.Column("substance", sa.String(length=100), nullable=True),
        sa.Column("lic_use_kind", sa.String(length=100), nullable=True),
        sa.Column("lic_use_desc", sa.String(length=100), nullable=True),
        sa.Column("lic_type", sa.String(length=50), nullable=True),
        sa.Column(
            "aggregated_reserved_ods_net_mass",
            sa.Float(precision=7, asdecimal=True),
            nullable=True,
        ),
        sa.Column(
            "aggregated_consumed_ods_net_mass",
            sa.Float(precision=7, asdecimal=True),
            nullable=True,
        ),
        sa.Column("date_created", sa.Date(), nullable=True),
        sa.Column("date_updated", sa.Date(), nullable=True),
        sa.Column("created_from_certex", sa.Boolean(), nullable=True),
        sa.Column("has_certex_data", sa.Boolean(), nullable=True),
        sa.ForeignKeyConstraint(
            ["multi_year_licence_id"],
            ["multi_year_licence.id"],
        ),
        sa.ForeignKeyConstraint(
            ["undertaking_id"],
            ["undertaking.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )


def downgrade():
    op.drop_table("multi_year_licence_aggregated")
    op.drop_table("substance_nomenclature_combined_nomenclature_link")
